name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: '1.13'
            otp: '24'
          - elixir: '1.17'
            otp: '27'
            lint: true
    steps:
      - name: Set up Elixir
        id: setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          version-type: strict

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        env:
          cache-name: cache-elixir-deps
        uses: actions/cache@v4
        with:
          key: ${{runner.os}}-mix-${{env.cache-name}}-${{steps.setup.outputs.otp-version}}-${{steps.setup.outputs.elixir-version}}-${{hashFiles('**/mix.lock')}}
          path: deps
          restore-keys: |
            ${{runner.os}}-mix-${{env.cache-name}}-${{steps.setup.outputs.otp-version}}-${{steps.setup.outputs.elixir-version}}-
            ${{runner.os}}-mix-${{env.cache-name}}-${{steps.setup.outputs.otp-version}}-
            ${{runner.os}}-mix-${{env.cache-name}}-

      - name: Cache compiled build
        id: cache-build
        env:
          cache-name: cache-compiled-build
        uses: actions/cache@v4
        with:
          key: ${{runner.os}}-mix-${{env.cache-name}}-${{steps.setup.outputs.otp-version}}-${{steps.setup.outputs.elixir-version}}-${{hashFiles('**/mix.lock')}}
          path: _build
          restore-keys: |
            ${{runner.os}}-mix-${{env.cache-name}}-${{steps.setup.outputs.otp-version}}-${{steps.setup.outputs.elixir-version}}-
            ${{runner.os}}-mix-${{env.cache-name}}-${{steps.setup.outputs.otp-version}}-
            ${{runner.os}}-mix-${{env.cache-name}}-

      - name: Clean if incremental build fails
        if: github.run_attempt != '1'
        run: |
          mix deps.clean --all
          mix clean

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Check unused deps
        run: mix deps.unlock --check-unused
        if: ${{matrix.lint}}

      - name: Check formatting
        run: mix format --check-formatted
        if: ${{matrix.lint}}

      - name: Check compilation errors
        run: mix compile --warnings-as-errors
        if: ${{matrix.lint}}

      - name: Run tests
        run: mix test
